### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by eng-dibo** [sindresorhus/strip-json-comments#52]
updating to node v16 where ES6 modules are supported, I got the following error caused by `strip-json-comments`
```
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/strip-json-comments/index.js from jest.config.ts not supported.

Instead change the require of index.js in jest.config.ts to a dynamic import() which is available in all CommonJS modules.

    at readConfigFileAndSetRootDir (node_modules/jest-config/build/readConfigFileAndSetRootDir.js:118:13)
    at async readConfig (node_modules/jest-config/build/index.js:233:18)
    at async readConfigs (node_modules/jest-config/build/index.js:420:26)
    at async runCLI (node_modules/@jest/core/build/cli/index.js:132:59)
    at async Object.run (node_modules/jest-cli/build/cli/index.js:155:37)
```

jest.config.ts
```
import stripJsonComments from 'strip-json-comments';
```

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
